##
## Copyright (c) 2022 TUM Department of Electrical and Computer Engineering.
##
## This file is part of MLonMCU.
## See https://github.com/tum-ei-eda/mlonmcu.git for further info.
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
name: Run Benchmarks in Docker Container
on:
  workflow_dispatch:
    inputs:
      bench_image:
        description: 'Base Docker Image'
        required: true
        default: "ghcr.io/tum-ei-eda/mlonmcu-bench:default-latest"
      bench_cmd:
        description: 'Benchmarking Command'
        required: true
        default: "flow run tinymlperf"

jobs:
  bench:
    name: Run a single benchmark
    runs-on: ubuntu-latest
    container: "${{ github.event.inputs.bench_image }}"
    steps:
    - name: Run Benchmark command in container
      run: python3 -m mlonmcu.cli.main ${{ github.event.inputs.bench_cmd }}
    - name: Store cmdline
      run: echo "${{ github.event.inputs.bench_cmd }}" >> /environment/results/cmd.txt
    - name: Archive reports
      uses: actions/upload-artifact@v2
      with:
        name: results
        path: /environment/results/
    # Pushing results to a branch is not possible right now as we are inside a docker container!
    # - name: Get date
    #   run: echo "timestamp=`date +%FT%T`" >> $GITHUB_ENV
    # - name: Install RSync
    #   run: apt install -y rsync
    # - name: Upload results to a special branch
    #   uses: JamesIves/github-pages-deploy-action@4.1.1
    #   with:
    #     folder: /environment/results/
    #     branch: benchmark_results
    #     target-folder: ${{ env.timestamp }}/
